### PR TITLE
Refactor aquatx.py and write unit tests

### LINKED ISSUE #8: Refactor aquatx.py
Refactor the main project entry point for unit test compatibility and consistency with the rest of the project

- [x] Implement a `get_args()` method using argparse
- [x] Split `main` into separate functions for run, get-template, setup-cwl, and setup-nextflow
- [x] Write unit tests using each of these new functions

### PR DESCRIPTION
**Pull request by AlexTate**
Closes #8

### CODE REVIEW

**Comment by AlexTate** [comment]
This currently looks much messier than it is due to the commits from issue-4 waiting to be merged with master.
issue-8 branched from issue-4, as this is currently the most up to date branch.
After the PR for issue-4 is approved and merged, the Changed Files list on this PR will be cleared up significantly

**Comment by AlexTate** [comment]
Toggled base branch to arbitrarily selected branch and back. This is the workaround for forcing GitHub to update the changed files list. This was necessary because issue-8 branched from another branch which was ahead of master, and has since been merged with master.

**Comment by AlexTate** [comment]
Currently working on proper Google style Docstrings in aquatx.py and unit_test_helpers.py. They will be pushed shortly -- please hold off on merging.

**Comment by AlexTate** [comment]
This is a beast of a PR. Should be ready.

Send it

**Comment by taimontgomery** [comment]
Looks good, nice work.

**Pull request merged**
