### PR TITLE
Remove Plotter from Pipeline

### PR DESCRIPTION
**Pull request by AlexTate**
All plotter components and references have been removed. This is a temporary change and these features will be reintroduced in a future commit.

Closes issue #3

### CODE REVIEW

**Comment by AlexTate** [comment]
I suspect some of these removals went beyond the intended scope of #3. There were some issues with plotter.py (namely size_dist_plot) which I believe should be later addressed under plotter-specific issues. 

In the spirit of keeping the master branch fully functional, I have decided to remove the plotter Python component and its CWL wrapper, rather than just removing the step from the workflow and configuration file.

**Comment by biokcb** [comment]
Yeah, I thought something simple would be quickest, but either works. The beauty of version control is that we can just go back here to re-implement plotter tools from the last spot based on what was removed or just restart it from scratch

**Comment by AlexTate** [comment]
Exactly!

**Comment by AlexTate** [comment]
Travis checks are failing on this branch but are resolved with the PR for issue 4

**Review by taimontgomery — APPROVED** [review]
We'll keep the plotting step on hold for now.

**Pull request merged**
